### ISSUE TITLE
AEP SDK Roku v1.2.0 Missing ~2000 lines of code, causing errors

### ISSUE THREAD

**Issue by jonathanruggiero** [adobe/aepsdk-roku#162]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-roku/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

My request is coming from Paramount.

We supplied the AEP Roku SDK to our client teams for installation. When the team attempted to install the upgrade in order to support the new features available, we noticed that ~2000 lines of code were removed between version 1.1.0 and version 1.1.0. When we attempt to initialize the SDK, the missing code creates exceptions and errors.

One of the errors we can see are as follows:
@ AEPSDK.brs Line=83, Function=adobeaepsdkinit()
_adb_logDebug("AdobeAEPSDKInit() - Initializing the SDK.")
_adb_logDebug function is not defined

### Environment

SDK Version: v1.2.0
OS: Roku 12.5

### Steps to reproduce

1. Observe v1.1.0 code of the AEP Roku SDK
2. Observe v1.2.0 code of the AEP Roku SDK
3. Observe that between the two SDKs, ~2000 lines of code have been removed

### Current behavior

We are experiencing errors due to redacted code

### Expected behavior

We expect that with the SDK upgrade that we do not lose functionality and introduce errors

**Comment by addb** [comment]
Hi @jonathanruggiero,

Did you download Source Code zip instead of AEPRokuSDK-1.2.0.zip? Please download and use AEPSDK.brs from [AEPRokuSDK-1.2.0.zip](https://github.com/adobe/aepsdk-roku/releases/download/1.2.0/AEPRokuSDK-1.2.0.zip) 

Thanks,
Arjun

**Comment by jonathanruggiero** [comment]
Thank you @addb - The team we are working with internally was able to resolve the issue with your guidance.
